# Generated by Django 3.2.14 on 2022-08-16 13:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sido', models.CharField(max_length=20)),
                ('sigungu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leaf82',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantname', models.CharField(max_length=20)),
                ('photo', models.ImageField(default='static/monstera.jpg', upload_to='images/leaf82/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=1000)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('category_class', models.CharField(choices=[('분양해요', '분양해요'), ('분양받아요', '분양받아요')], default='분양해요', max_length=5)),
                ('status_class', models.CharField(choices=[('분양대기', '분양대기'), ('분양완료', '분양완료'), ('분양예약', '분양예약')], default='분양대기', max_length=4)),
                ('posting_addr', models.IntegerField(default=0)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaf82.juso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
